### ISSUE TITLE
Als gemeente wil kunnen aangeven of de betrokkene een gemachtigde/bewindvoerder was

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#107]
... en eventueel zijn/haar rol/categorie.

TODO: Eerst testomgeving, dan speccen.

**Comment by joeribekker** [comment]
Geblokkeerd door ontbreken van DigiD-machtigen en eHerkenning-bewindvoering test omgeving. Dit ligt bij Den Haag / Rotterdam.

**Comment by joeribekker** [comment]
Assigning Anna to keep track in her column but sergei will write the spec for OK and OZ because the Machtigen spec itself is done.

**Comment by annashamray** [comment]
The discussion and implementation of Machtigen are done in https://github.com/open-zaak/open-zaak/issues/1733
