### ISSUE TITLE
Upgrade to Django 4.2

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/open-klant#130]
Checklist to prepare the Django 4.2 LTS upgrade

**3rd party packages to verify/make compatible**

- [ ] commonground-api-common - needs 4.2 support, and depends on drf-yasg etc. which is problematic
- [x] django-admin-index - ok
- [ ] django-axes
    - version is okay
    - however, it is not specified as `django-axes[ipware]` so ipware is not pulled in, yet there are settings referring to ipware
    - possibly the reverse proxy setup is broken to determine the IP address because of this
    - it also uses legacy django axes settings like `AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP`
    - might just not be working properly at all
- [ ] django-better-admin-arrayfield -> needs to be replaced, see https://github.com/open-formulieren/open-forms/pull/3737 for the involved changes
- [x] django-cors-headers - ok
- [ ] django-db-logger - uncertain, does not appear [to be tested](https://github.com/CiCiUi/django-db-logger/blob/master/.github/workflows/db-logger.yml#L11) on Django newer than 3.2 but latest release was end of 2023
- [ ] django-loose-fk - no support, but seems to be scheduled for removal in #128 
- [x] django-markup - ok
- [x] django-redis - ok
- [x] django-rosetta - ok
- [ ] djangorestframework - 3.14 added support for Django 4.1, 4.2 should work too (according to Github)
    - this also massively affects drf-yasg, which is being removed in favour of spectacular in #120 
    - switch to spectacular may upgrade this from 3.12 to 3.14
- [x] elastic-apm - ok
- [ ] mozilla-django-oidc-db - requires v0.14.0, see also #129 
- [x] psycopg2 - [current version is supported](https://docs.djangoproject.com/en/4.2/ref/databases/#postgresql-notes), upgrading to psycopg 3 is viable though
- [x] sentry_sdk - ok
- [x] zgw-consumers - ok

**3rd party packages (planned) to be dropped?**

- [ ] click - doesn't seem to be used anywhere
- [ ] jq - doesn't seem to be used anywhere
- [ ] jsonschema - doesn't seem to be used anywhere
- [ ] dictdiffer - doesn't seem to be used anywhere
- [ ] python-dateutil - doesn't seem to be used anywhere
- [ ] requests - used by third party packages, but no direct usage -> can be removed from `base.in`
- [ ] requests-cache - doesn't seem to be used anywhere
- [ ] self-certifi - doesn't seem to be used
- [ ] bleach - doesn't seem to be used
- [ ] django-extra-views - doesn't seem to be used
- [x] django-log-outgoing-requests - ok but doesn't seem to be used
- [ ] django-sniplates - dead code only it seems

**Open Klant itself**

- [ ] `src/openklant/scss/admin/admin_overrides.scss` does not yet make use of the CSS variables for colors, which will lead to (likely) unusable dark theme
    - a better but incomplete setup can be taken from OF
    - https://github.com/open-formulieren/open-forms/blob/master/src/openforms/scss/admin/_app_overrides.scss#L11
    - https://github.com/open-formulieren/open-forms/blob/master/src/openforms/scss/admin/_admin_theme.scss#L59
    - these admin overrides need a revisit anyway and probably we should check what the state of them is in default-project
- [x] Did not find any usage of removed `ugettext*` functions

**Comment by stevenbal** [comment]
upgrade was done in https://github.com/maykinmedia/open-klant/pull/169
