### ISSUE TITLE
Als KISS-ontwikkelaar wil ik een contactmoment kunnen registreren

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#135]
> 1. Registreer Contactmoment  (en evt. daarbij horende Contactverzoek)
> Input:
> a. Inhoud van het contactmoment (vraag, gekoppelde bronnen, toelichting; kan meerdere zijn als er tijdens het Klantcontact meer dan 1 vraag/onderwerp werd besproken, referenties naar gekoppelde Zaak).  
> b. de Betrokkene bij het Contactmoment, evt. incl de juiste referentie naar een Klant;  
> c. de interne taak of taken (vooral: Contactverzoek) die voortkwamen uit dat contactmoment.  

**Stakeholder**: KISS/ICATT

**Comment by bart-maykin** [comment]
U kan de "contactmoment" aanmaken door middel van de volgende endpoint:
POST /klantinteracties/api/v1/klantcontacten

Om "contactverzoeken" aan te maken en koppelen aan het "contactmoment" dan moet u de UUID van het "contactmoment" gebruiken in het veld "aanleidinggevendKlantcontact":
POST /klantinteracties/api/v1/internetaken

Om "gekoppelde zaak" en "gekoppelde bronnen" aan te maken en koppelen aan het "contactmoment" dan moet u de UUID van het "contactmoment" gebruiken in het veld "klantcontact":
POST /klantinteracties/api/v1/onderwerpobjecten

Om "betrokkene" aan te maken en koppelen aan het "contactmoment" dan moet u de UUID van het "contactmoment" gebruiken in het veld "hadKlantcontact":
POST /klantinteracties/api/v1/betrokkenen

Om een "klant" te koppelen aan de "betrokkenen" dan moet u de UUID van de "betrokkenen" gebruiken in het veld "betrokkenen":
- nieuwe klant: POST /klantinteracties/api/v1/partijen
- bestaande klant: UPDATE/PATCH /klantinteracties/api/v1/partijen

**Comment by joeribekker** [comment]
Akkoord
