### ISSUE TITLE
Als KISS-ontwikkelaar wil ik openstaande interne taken obv digitaal adres willen opvragen

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#136]
> 2. Zoek openstaande, en de afgelopen x aantal dagen afgeronde, Contactverzoeken (interne taak) op, o.b.v. (exact) telefoonnr / e-mailadres van de betrokkene,
> a. Resultaat: een lijst met Contactverzoeken, met daarbij alle informatie die hoort bij elk Contactverzoek (betrokkene-gegevens, evt. klant, Actor die het Contactverzoek onder handen heeft, inhoud vh contactmoment waaruit het Contactverzoek is ontstaan). 
> b. Gesorteerd op meest recente bovenaan

**Stakeholder**: KISS/ICATT

**Comment by bart-maykin** [comment]
De informatie kan opgehaald worden vanuit de "betrokkenen" endpoint (maar niet op basis van "afgelopen x aantal dagen"):
GET /klantinteracties/api/v1/betrokkenen?verstrektedigitaalAdres__adres=(adres)

hier mee kunt u alle UUID's ophalen en met dat alle contactverzoeken ophalen door middel van:
GET /klantinteracties/api/v1/internetaken?klantcontact__uuid=(uuid van vorrige stap)

Als u extra informatie wilt zoals:
- klanten, dan kunt u dat doen vanuit de "betrokkenen" door middel van de UUID van het veld "wasPartij" en de volgende call:
  GET /klantinteracties/api/v1/partijen/{uuid}
- actoren, dan kunt u dat doen vanuit de "internetaken" door middel van de UUID van het veld "toegewezenAanActor" en de volgende call:
  GET /klantinteracties/api/v1/actoren/{uuid}
- contactverzoek, dan kunt u dat doen door middel van:
  - GET /klantinteracties/api/v1/internetaken?klantcontact__uuid=(uuid van klantcontact)
  - GET /klantinteracties/api/v1/internetaken?klantcontact__nummer=(nummer van klantcontact)

**Comment by joeribekker** [comment]
Akkoord
