### ISSUE TITLE
Als KISS-ontwikkelaar wil ik kunnen zoeken op BRP/KvK gegevens

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#137]
> Zoek Klanten op BRP-gegevens of KvK-gegevens
> Resultaat: overzicht van Klanten met in dat resultaat hun BRP gegevens / KvK gegevens, en hun contactgegevens

**Stakeholder**: KISS/ICATT

**Comment by bart-maykin** [comment]
Ja dit kan vanuit de "partijen" endpoint:
- Voor het ophalen van de BRP gegevens moet u het volgende doen:
	  GET /klantinteracties/api/v1/partijen?soortPartij=persoon&partijIdentificator__register=BRP
	  hier mee kunt u alle UUID's ophalen van de `partijIdentificatoren` veld en hiermee alle BRP gegevens ophalen door middel van:
	  GET /klantinteracties/api/v1/partij-identificatoren/{uuid}.
	 
- Voor het ophalen van de KvK gegevens moet u het volgende doen:
	  GET /klantinteracties/api/v1/partijen?soortPartij=organisatie&partijIdentificator__register=KvK
	  hier mee kunt u alle UUID's ophalen van de `partijIdentificatoren` veld en hiermee alle KvK gegevens ophalen door middel van:
 	  GET /klantinteracties/api/v1/partij-identificatoren/{uuid}.

**Comment by joeribekker** [comment]
Akkoord.
