### ISSUE TITLE
Als KISS-ontwikkelaar wil ik een klantbeeld kunnen opvragen

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#138]
> 4. Toon klantbeeld van een Klant
> Resultaat: een pagina waarop de volgende gegevens van een Klant te zien zijn : 
> i.    Naam en adres van de Klant.
> ii.    Contactgegevens van de Klant
> iii.    De contactmomenten (incl. inhoud) van die Klant, van de afgelopen xxx weken
> iv.    Openstaande contactverzoeken van die Klant (incl. inhoud, actor, status), incl. de contactverzoeken die de afgelopen xxx dagen zijn afgesloten
> v.    Lopende zaken van die Klant

**Comment by bart-maykin** [comment]
U kan de "klant" gegevens ophalen door middel van:
	GET /klantinteracties/api/v1/partijen?soortPartij=(persoon/contactpersoon)
Voor de "Contactgegevens" en "contactmomenten" informatie moet u het volgende doen:
- De "Contactgegevens" gegevens kunt u ophalen door middle van de gekopelde UUID's te gebruiken van "digitaleAdressen" met
  GET /klantinteracties/api/v1/digitaleadressen/{uuid}
- De "contactmomenten" gegevens kunt u ophalen door middle van de gekopelde UUID's te gebruiken van "betrokkenen" met
  GET /klantinteracties/api/v1/betrokkenen/{uuid}
  Voor de "contactverzoeken" en "Lopende zaken" informatie moet u het volgende doen:
  - De "contactverzoeken" gegevens kunt u ophalen door middle van de UUId van "betrokkenen" te gebruiken met
    GET /klantinteracties/api/v1/internetaken?klantcontact__uuid=(uuid)
  	- De "lopende zaken" gegevens kunt u ophalen door middle van de gekopelde UUID's te gebruiken van "gingOverOnderwerpobjecten" te gebruiken met
  	  GET /klantinteracties/api/v1/onderwerpobjecten/{uuid}

U kan alleen niet contactverzoek filteren op xxx dagen afgesloten.

**Comment by joeribekker** [comment]
Volgens mij kom je met expand nog verder met minder calls.

**Comment by sytskevanhasselt** [comment]
Mogelijk zie ik iets over het hoofd. Maar in de comment van 18 januari staat: 

> U kan de "klant" gegevens ophalen door middel van:
> GET /klantinteracties/api/v1/partijen?soortPartij=(persoon/contactpersoon)

Zoals ik het lees, is dit een call die alle Partijen geeft van soortPartij=persoon en/of soortPartij=contactpersoon
Voor een klantbeeld van een persoon wil je één specifiek persoon kunnen opvragen. Moet er niet nog iets van een identificerend gegeven bij?
