### ISSUE TITLE
Filter klantcontacten op onderwerpobject

### ISSUE THREAD

**Issue by ThomasMinkeRitense** [maykinmedia/open-klant#146]
### Omschrijving / Description

Als Zaakbehandelaar in GZAC
Wil ik een API endpoint om alle klantcontacten op te halen die horen bij een Zaak
Zodat die contactmomenten getoond kunnen worden bij de details van het zaakdossier

### Added value / Toegevoegde waarde

Deze functie geeft de zaakbehandelaar inzicht in alle contacten met de klant.

**Comment by joeribekker** [comment]
@bart-maykin Klantcontacten filteren op onderwerpobject__identificator props.
