### ISSUE TITLE
Gecombineerd API endpoint om klantcontact, betrokkene en onderwerpobject te maken

### ISSUE THREAD

**Issue by ThomasMinkeRitense** [maykinmedia/open-klant#147]
### Omschrijving / Description

Als GZAC ontwikkelaar
Wil ik een API endpoint die in een keer een betrokkene, onderwerpobject en klantcontact aanmaakt
Zodat ik niet drie requests achter elkaar hoef te doen

### Added value / Toegevoegde waarde

Als er in GZAC een klantcontact wordt aangemaakt bij een lopende Zaak, moeten er drie requests achter elkaar gedaan worden. Deze combineren zorgt voor betere performance en een minder complexe integratie.

**Comment by joeribekker** [comment]
Voor create gaan we nu geen convenience resource aanmaken. 3 API calls voor een aanmaak-actie lijkt me geen enkel probleem. Niet voor developers en niet voor de business (bijv. Performance)

**Comment by joeribekker** [comment]
Estimate: 3-4 days.

@JanBrek needs approval.

**Comment by joeribekker** [comment]
@JanBrek ping

**Comment by PeterVanBragt** [comment]
To what extend will this feature be covered by the 'Integraal klantbeeld' that's planned for?

**Comment by joeribekker** [comment]
@PeterVanBragt Please point me to the ticket that describes this and its timeline - For me, this is unknown so I have no way to answer you

**Comment by PeterVanBragt** [comment]
Discussed with Jan Verbeek and he agrees that this ticket should be picked up. However, looking for budget so no approval yet.

**Comment by PeterVanBragt** [comment]
@joeribekker  Approved!
