### ISSUE TITLE
Query parameters diffen tussen API spec VNG en Open Klant

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#159]
Ik wil een lijstje hebben met welke query Paramus wij hebben vs VNG. Ian je dat in dit ticket in kaart brengen per list resource?

**Comment by bart-maykin** [comment]
endpoint (naam)

- [ ] + hebben wij
- [ ] - hebben we niet
- [ ] ~ naam weiziging 

Actoren:
- [ ] - actoridentificator__codeRegister
- [ ] ~ actoridentificator__objectId -> objectidentificator_object_id
- [ ] ~ actoridentificator__codeObjecttype -> objectidentificator_objecttype
- [ ] ~ actoridentificator__codeSoortObjectId -> objectidentificator_soort_object_id

Betrokkenen:
- [ ] - contactnaam_achternaam
- [ ] - contactnaam_voorletters
- [ ] - contactnaam_voornaam
- [ ] - contactnaam_voorvoegselAchternaam
- [ ] - bezoekadres_adresregel1
- [ ] - bezoekadres_adresregel2
- [ ] - bezoekadres_adresregel3
- [ ] - bezoekadres_codeLand
- [ ] - bezoekadres_nummeraanduidingid
- [ ] - correspondentieadres_adresregel1
- [ ] - correspondentieadres_adresregel2
- [ ] - correspondentieadres_adresregel3
- [ ] - correspondentieadres_codeLand
- [ ] - correspondentieadres_nummeraanduidingid
- [ ] - rol
- [ ] - initiator
- [ ] - organisatienaam
- [ ] ~ hadKlantcontact -> klantcontact__uuid
- [ ] ~ wasPartij -> was_partij__uuid
- [ ] + klantcontact__nummer
- [ ] + klantcontact__url
- [ ] + verstrektedigitaal_adres__adres
- [ ] + verstrektedigitaal_adres__url
- [ ] + verstrektedigitaal_adres__uuid
- [ ] + was_partij__nummer
- [ ] + was_partij__url


Bijlagen:
- [ ] - bijlageidentificator_codeRegister
- [ ] - wasBijlageVanKlantcontact
- [ ] ~ bijlageidentificator_objectId -> objectidentificator_object_id
- [ ] ~ bijlageidentificator_codeObjecttype -> objectidentificator_objecttype
- [ ] ~ bijlageidentificator_codeSoortObjectId -> objectidentificator_soort_object_id


Digitale adressen:
- [ ] - adres
- [ ] - omschijving
- [ ] - verstrektDoorBetrokkene
- [ ] - verstrektDoorPartij

Interne taken:
- [ ] - gevraagdeHandeling
- [ ] - toelichting
- [ ] - verwerktOp
- [ ] - toegewezenAanActor
- [ ] ~ aanleidinggevendKlantcontact -> klantcontact__uuid
- [ ] + klantcontact__nummer
- [ ] + actor__naam

Klantcontacten:
- [ ] - plaatsgevondenOp
- [ ] - indicatieContactGelukt
- [ ] - vertrouwelijk
- [ ] + had_betrokkene__url
- [ ] + had_betrokkene__uuid
- [ ] + kanaal
- [ ] + onderwerpobject__objectidentificator_object_id
- [ ] + onderwerpobject__objectidentificator_objecttype
- [ ] + onderwerpobject__objectidentificator_register
- [ ] + onderwerpobject__objectidentificator_soort_object_id
- [ ] + onderwerpobject__url
- [ ] + onderwerpobject__uuid

Onderwerpobjecten:
- [ ] - onderwerpobjectidentificator_codeRegister
- [ ] - onderwerpWasKlantcontact
- [ ] - wasOnderwerpVanKlantcontact
- [ ] ~ onderwerpobjectidentificator_objectId -> objectidentificator_object_id
- [ ] ~ onderwerpobjectidentificator_codeObjecttype -> objectidentificator_objecttype
- [ ] ~ onderwerpobjectidentificator_codeSoortObjectId -> objectidentificator_soort_object_id

Partij-Identificatoren:
- [ ] - anderePartij-identificator
- [ ] - partij-identificator_objectId
- [ ] - partij-identificator_codeObjecttype
- [ ] - partij-identificator_codeRegister
- [ ] - partij-identificator_codeSoortObjectId
- [ ] - identificeerdePartij

Partijen:
- [ ] - interneNotitie
- [ ] - voorkeursDigitaalAdres
- [ ] - vertegenwoordigdePartij (bestaat binnen koppel tabel Vertegenwoordigingen)
- [ ] ~ bezoekadres_codeLand -> bezoekadres_land 
- [ ] ~ correspondentieadres_codeLand -> correspondentieadres_land
- [ ] ~ werkteVoorPartij -> werkt_voor_partij__uuidwerkt_voor_partij__uuid
- [ ] + categorierelatie__categorie__naam
- [ ] + partij_identificator__object_id
- [ ] + partij_identificator__objecttype
- [ ] + partij_identificator__register
- [ ] + partij_identificator__soort_object_id
- [ ] + werkt_voor_partij__nummer
- [ ] + werkt_voor_partij__url

**Comment by joeribekker** [comment]
Mooi overzicht Bart! Ik heb je lijst gekopieerd en voorzien van mijn insteek:

Actoren:
- [ ] - actoridentificator__codeRegister (graag toevoegen, overal bij identificators)
- [ ] ~ actoridentificator__objectId -> objectidentificator_object_id  (graag hernoemen)
- [ ] ~ actoridentificator__codeObjecttype -> objectidentificator_objecttype  (graag hernoemen)
- [ ] ~ actoridentificator__codeSoortObjectId -> objectidentificator_soort_object_id  (graag hernoemen)

Betrokkenen:
- [ ] - contactnaam_achternaam  (graag toevoegen)
- [ ] - contactnaam_voorletters  (graag toevoegen)
- [ ] - contactnaam_voornaam  (graag toevoegen)
- [ ] - contactnaam_voorvoegselAchternaam  (graag toevoegen)
- [ ] ~- bezoekadres_adresregel1~ (keuze: achterwege laten, niet gespecificeerd veld doorzoeken is onhandig en waarom zoeken op specifiek adres?)
- [ ] ~- bezoekadres_adresregel2~ (keuze: achterwege laten)
- [ ] ~- bezoekadres_adresregel3~ (keuze: achterwege laten)
- [ ] ~- bezoekadres_codeLand~ (keuze: achterwege laten, niet nuttig?)
- [ ] ~- bezoekadres_nummeraanduidingid~ (keuze: achterwege laten, zoeken op specifiek adres, waarom?)
- [ ] ~- correspondentieadres_adresregel1~ (keuze: achterwege laten, zoeken op specifiek adres, waarom?)
- [ ] ~- correspondentieadres_adresregel2~ (keuze: achterwege laten)
- [ ] ~- correspondentieadres_adresregel3~ (keuze: achterwege laten)
- [ ] ~- correspondentieadres_codeLand~ (keuze: achterwege laten)
- [ ] ~- correspondentieadres_nummeraanduidingid~ (keuze: achterwege laten)
- [ ] ~- rol~ (keuze: geen meerwaarde?)
- [ ] ~- initiator~ (keuze: geen meerwaarde?)
- [ ] - organisatienaam  (graag toevoegen)
- [ ] ~ hadKlantcontact -> klantcontact__uuid  (graag hernoemen naar `had_klantcontact_uuid` maar met camelCase uiteraard)
- [ ] ~\~ wasPartij -> was_partij__uuid~ (geen issue)
- [ ] + klantcontact__nummer (graag hernoemen naar `had_klantcontact_nummer` maar met camelCase uiteraard)
- [ ] + klantcontact__url (graag hernoemen naar `had_klantcontact_url` maar met camelCase uiteraard)
- [ ] ~+ verstrektedigitaal_adres__adres~ (keuze: behouden)
- [ ] ~+ verstrektedigitaal_adres__url~ (keuze: behouden)
- [ ] ~+ verstrektedigitaal_adres__uuid~ (keuze: behouden)
- [ ] ~+ was_partij__nummer~ (keuze: behouden)
- [ ] ~+ was_partij__url~ (keuze: behouden)


Bijlagen:
- [ ] - bijlageidentificator_codeRegister (graag toevoegen, overal bij identificators)
- [ ] ~- wasBijlageVanKlantcontact~ (nvt)
- [ ] ~ bijlageidentificator_objectId -> objectidentificator_object_id (hernoemen naar VNG variant)
- [ ] ~ bijlageidentificator_codeObjecttype -> objectidentificator_objecttype (hernoemen naar VNG variant)
- [ ] ~ bijlageidentificator_codeSoortObjectId -> objectidentificator_soort_object_id (hernoemen naar VNG variant)


Digitale adressen:
- [ ] ~- adres~ (keuze: behouden)
- [ ] ~- omschijving~ (keuze: behouden)
- [ ] ~- verstrektDoorBetrokkene~ (keuze: behouden)
- [ ] ~- verstrektDoorPartij~ (keuze: behouden)

Interne taken:
- [ ] ~- gevraagdeHandeling~ (keuze: geen meerwaarde?)
- [ ] ~- toelichting~ (keuze: geen meerwaarde?)
- [ ] - verwerktOp (graag toevoegen)
- [ ] - toegewezenAanActor (graag toevoegen: `toegewezen_aan_actor_uuid` en `...url`)
- [ ] ~ aanleidinggevendKlantcontact -> klantcontact__uuid (hernoemen naar VNG variant)
- [ ] ~+ klantcontact__nummer~ (keuze: behouden)
- [ ] ~+ actor__naam~ (keuze: behouden)

Klantcontacten:
- [ ] - plaatsgevondenOp (graag toevoegen)
- [ ] - indicatieContactGelukt (graag toevoegen)
- [ ] - vertrouwelijk (graag toevoegen)
- [ ] ~+ had_betrokkene__url~ (keuze: behouden)
- [ ] ~+ had_betrokkene__uuid~ (keuze: behouden)
- [ ] ~+ kanaal~ (keuze: behouden)
- [ ] ~+ onderwerpobject__objectidentificator_object_id~ (keuze: behouden)
- [ ] ~+ onderwerpobject__objectidentificator_objecttype~ (keuze: behouden)
- [ ] + onderwerpobject__objectidentificator_register (hey, hebben we `register` hier wel?)
- [ ] ~+ onderwerpobject__objectidentificator_soort_object_id~ (keuze: behouden)
- [ ] ~+ onderwerpobject__url~ (keuze: behouden)
- [ ] ~+ onderwerpobject__uuid~ (keuze: behouden)

Onderwerpobjecten:
- [ ] - onderwerpobjectidentificator_codeRegister (graag toevoegen)
- [ ] ~- onderwerpWasKlantcontact~ (keuze: geen meerwaarde?)
- [ ] ~- wasOnderwerpVanKlantcontact~ (keuze: geen meerwaarde?)
- [ ] ~ onderwerpobjectidentificator_objectId -> objectidentificator_object_id (hernoemen naar VNG variant)
- [ ] ~ onderwerpobjectidentificator_codeObjecttype -> objectidentificator_objecttype (hernoemen naar VNG variant)
- [ ] ~ onderwerpobjectidentificator_codeSoortObjectId -> objectidentificator_soort_object_id (hernoemen naar VNG variant)

Partij-Identificatoren:
- [ ] - anderePartij-identificator (graag toevoegen)
- [ ] - partij-identificator_objectId (graag toevoegen)
- [ ] - partij-identificator_codeObjecttype (graag toevoegen)
- [ ] - partij-identificator_codeRegister (graag toevoegen)
- [ ] - partij-identificator_codeSoortObjectId (graag toevoegen)
- [ ] ~- identificeerdePartij~ (geen idee wat dit is... ook onbekend in het IM)

Partijen:
- [ ] ~- interneNotitie~ (keuze: we gaan toch niet zoeken in interne notities?)
- [ ] ~- voorkeursDigitaalAdres (keuze: laat maar even zitten, wil een use case)
- [ ] - vertegenwoordigdePartij (bestaat binnen koppel tabel Vertegenwoordigingen) (kan je deze toevoegen met `vertegenwoordigde_partij uuid` en `vertegenwoordigde_partij_url`?)
- [ ] ~\~ bezoekadres_codeLand -> bezoekadres_land~
- [ ] ~\~ correspondentieadres_codeLand -> correspondentieadres_land~
- [ ] ~\~ werkteVoorPartij -> werkt_voor_partij__uuid / werkt_voor_partij__url~
- [ ] ~+ categorierelatie__categorie__naam~ (keuze: behouden)
- [ ] ~+ partij_identificator__object_id~ (keuze: behouden)
- [ ] ~+ partij_identificator__objecttype~ (keuze: behouden)
- [ ] ~+ partij_identificator__register~ (keuze: behouden)
- [ ] ~+ partij_identificator__soort_object_id~ (keuze: behouden)
- [ ] + werkt_voor_partij__nummer (graag hernoemen naar `werkte...` veld ook als het niet zo heet)
- [ ] + werkt_voor_partij__url (graag hernoemen naar `werkte...` veld ook als het niet zo heet)
