### ISSUE TITLE
Zelf kunnen bepalen hoeveel resultaten in response

### ISSUE THREAD

**Issue by flinden68** [maykinmedia/open-klant#173]
### Omschrijving / Description

Zou fijn zijn dat we een pageSize mee kunnen geven aan de api calls om controle te hebben over hoeveel resultaten we terug krijgen

### Added value / Toegevoegde waarde

Meer controle over de paginatie in de frontend

**Comment by joeribekker** [comment]
Good idea! But needs stakeholder

**Comment by joeribekker** [comment]
Estimate: 1 day to add `pageSize`

**Comment by joeribekker** [comment]
See also open-zaak/open-zaak#1668 for the OZ version.

**Comment by joeribekker** [comment]
Picked up under open-zaak/open-zaak#1668 to do the library, then it will can also be done for Open Klant.
