### ISSUE TITLE
Hoe klant ophalen op basis van BSN/KVKNummer

### ISSUE THREAD

**Issue by flinden68** [maykinmedia/open-klant#174]
### Product versie / Product version

0.0.3

### Omschrijf het probleem / Describe the bug

Momenteel gebruiken we OpenKlant 1.x en halen we klant op basis van BSN en KvkNummer door deze mee te geven in als querystring parameter,  subjectNatuurlijkPersoon__inpBsn, subjectNatuurlijkPersoon__anpIdentificatie

Hoe gaat dat in OpenKlant 2.0? Kan dat nog steeds met 1 call?

**Comment by joeribekker** [comment]
Open Klant < 2.0 is no longer supported (and always had a concept standard) and we advise to migrate away from it. In 2.0 you can still do this with query param, see the Open API specs.

**Comment by flinden68** [comment]
Ja dat snap, alleen kan nergens documentatie voor OpenKlant2.0 vinden hoe je nu een klant/partij ophaalt op basis van bijvoorbeeld een bsn

**Comment by joeribekker** [comment]
Ik zal deze wel een keer opnemen in de documentatie, zal wel meer gevraagd worden :)

1. "Klant" bestaat niet meer en is nu "Partij" geworden
2. Partij kan gekoppeld worden aan allerlei registraties, waaronder de BRP (maar ook KvK, Medewerker-register, RNI, Contactgegevens API, etc.)
3. De koppeling wordt gerealiseerd met een "identificator" (gebeurt op paar plekken).

Komt neer op:

``` 
api/v1/partijen?partijIdentificator__codeSoortObjectId=bsn&partijIdentificator__objectId=111222333
```

Kan je daarmee verder?

**Comment by flinden68** [comment]
@joeribekker  zie nu pas je reactie over hoe een 'partij' op te halen. Denk zeker dat er behoefte zal zijn aan documentatie om   op basis van een BSN of KVK nummer 'partijen' op te halen.

Als ik je voorbeeld zie, is 111222333 dan de BSN??

**Comment by joeribekker** [comment]
> Als ik je voorbeeld zie, is 111222333 dan de BSN??

Correct, dat is een valide test BSN :)
