### ISSUE TITLE
Voorkeurskanaal toevoegen

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#177]
Ingediend door: Dimpact / Rotterdam

> Bij het doornemen van de nieuwe versie van OpenKlant kwamen wij tot de conclusie dat het attribuut "Voorkeurskanaal" niet is opgenomen in het datamodel. Wel is er een veld "voorkeursdigitaaladres".
> 
> Wij wilden dit veld gebruiken om in combinatie met Podium D Formulier (Openforms) de WMEBV in te richten. Het  voorkeurskanaal moet dan bv de waarde bevatten : Balie, Telefonie, Mail, Berichtenbox.
> 
> Is er een bepaalde reden waarom dit niet is opgenomen en/of is er nog een mogelijkheid dit alsnog door te voeren in een volgende versie?

**Comment by joeribekker** [comment]
Graag toevoegen: `voorkeursKanaal` net zoals digitaleAdressen vs voorkeursDigitaalAdres.

**Comment by joeribekker** [comment]
Dit moet verduidelijkt worden, want VNG heeft volgens mij bedacht dat digitaalAdres hetzelfde is als kanaal...

**Comment by joeribekker** [comment]
@joeridiederen zie: https://vng-realisatie.github.io/klantinteracties/informatiemodel/gegevenswoordenboek

![image](https://github.com/maykinmedia/open-klant/assets/96970/675b6f7c-361c-4b72-9e68-301d227dcfeb)

En anders bij Johan Boer vragen :)

**Comment by joeridiederen** [comment]
@joeribekker wens mag ingetrokken worden. Vanuit Rotterdam is besloten om te conformeren aan het attribuut 'digitaaladres', zoals reeds opgenomen in Open Klant.
