### ISSUE TITLE
Taak kunnen toewijzen aan medewerker én een organisatorische eenheid

### ISSUE THREAD

**Issue by mariusvandam** [maykinmedia/open-klant#182]
### Thema / Theme

Klantinteracties API

### Omschrijving / Description

Als werkverdeler binnen de gemeente
wil ik dat een Interne Taak naast een medewerker ook binnen een specifieke afdeling (organisatorische eenheid) wordt toegewezen
zodat ik deze taak kan zien binnen het geheel van werkzaamheden van mijn team en kan toewijzen aan een beschikbare collega
 

### Aanvullende opmerkingen / Additional context

Voor details zie https://github.com/VNG-Realisatie/klantinteracties/issues/284

**Comment by joeribekker** [comment]
@mariusvandam dit kan toch al?

![image](https://github.com/maykinmedia/open-klant/assets/96970/df493aeb-3140-4f69-aaca-1f60a01a4dbf)

**Comment by sytskevanhasselt** [comment]
Hoi Joeri,
In bovenstaand model is de Actor óf een medewerker, óf een organisatorische eenheid.  
De wens is om, áls het gaat om een medewerker is, óók een organistorische éénheid mee te kunnen geven. 

In het issue bij klantinteracties staat wat meer toelichting: 

> **Scenario**
> Neem deze situatie: Paul werkt bij de afdeling Budgetadvies, en daarbinnen/daarnaast ook binnen de subafdeling Schuldhulpverlening.
> Als er nu een client belt van schuldhulpverlening, dan weet die dat Paul zijn/haar casemanager is.
> 
> Het is wenselijk dat een interne taak / contactverzoek op naam van “Paul" komt te staan én op de afdeling Schuldhulpverlening.
> 
> Als Paul werkt, dan ziet hij deze taak snel in de eigen werkvoorraad.
> Als Paul om niet werkt (ziekte, vakantie, geen werkdag) dan zien zijn collega-schuldhulpverleners (of een werkverdeler) dat één van de cliënten van Paul teruggebeld moet worden.
> Als deze taak in de werkvoorraad van de overkoepelende afdeling Budgetadvies terecht komt, dan is de kans reëel, dat deze taak minder snel wordt opgepakt.

**Comment by joeribekker** [comment]
@sytskevanhasselt 

Helder. In ons gesprek op De.vloer gaf je nog een ander inzicht op mijn vraag: "Waarom leidt je de afdeling niet af Paul?" Je antwoord was zoiets als: "Omdat Paul voor meerdere afdelingen kan werken en het daarom niet duidelijk is in welke generieke werkbak de taak terecht moet komen."

Dus, late we een `InterneTaak.toegewezenAanActor` omzetten naar een lijst van `toegewezenAanActoren` zodat je Paul en de afdeling kan toevoegen. Akkoord?

**Comment by mariusvandam** [comment]
@joeribekker en @sytskevanhasselt volgens mij lost dat inderdaad ons issue op: ale er meerdere actoren op één taak mogelijk zijn kunnen we én een afdeling én een medewerker toewijzen. 
Dit maakt in potentie ook mogelijk dat meerdere medewerkers worden gekoppeld aan één taak. Of dat in de praktijk wenselijk is weet ik niet.

**Comment by joeribekker** [comment]
Refinement with team: Change object to array for `toegewezenAanActor` within "Interne Taak".
This however is a breaking change :(

A non-breaking way might be:

We add `toegewezenAanActoren` (notice the "en" at the end) as a new property.
If you add a `toegewezenAanActor` it will also show up first in the list.
If you add multiple `toegewezenAanActoren` then the first item will be shown in `toegewezenAanActor`.

Estimate: 3 days.

@mariusvandam Waiting for approval

**Comment by joeribekker** [comment]
Refinement: Bovenstaande is akkoord. We maken `toegewezenAanActor` DEPRECATED (kijk even naar de constructie in Open Zaak hoe deprecated te maken) en voeg toe `toegewezenAanActoren` maar minimaal 1 actor is verplicht, en het mogen er meer zijn.

**Comment by alextreme** [comment]
PR is onhold, the specification isn't complete enough and the resulting confusion means that this need further discussion with Joeri after his holiday
