### ISSUE TITLE
openapi.yaml 2.1.0: properties bij POST van een betrokkene

### ISSUE THREAD

**Issue by sytskevanhasselt** [maykinmedia/open-klant#205]
### Product versie / Product version

2.1.0

### Omschrijf het probleem / Describe the bug

In de openapi.yaml, staat bij de POST op /betrokkenen het volgende: 
![image](https://github.com/user-attachments/assets/247e57ed-d7dd-44a2-96aa-a850f35f3e6a)

Bij het object `hadKlantcontact` staat als omschrijving: "Persoon of organisatie die betrokken was bij een klantcontact." en in het object staat één `uuid`, met omschrijving: "Unieke (technische) identificatiecode van de betrokkene bij klantcontact.."

Ik vroeg mij af of je hier niet moet verwijzen naar `klantcontact` waar deze `betrokkene` bijhoort?  
Want de betrokkene bij het klantcontact ben je toch aan het registreren met deze POST? En de uuid ervan krijg je terug in de response? 

Of zie ik iets heel erg over het hoofd? 

### Stappen om te reproduceren / Steps to reproduce

1. Ga naar: https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/maykinmedia/open-klant/2.1.0/src/openklant/components/klantinteracties/openapi.yaml#tag/klanten-contacten/operation/klantcontactenCreate

**Comment by joeribekker** [comment]
Refinement: Help tekst aanpassen van `hadKlantcontact` naar "Het klantcontact waar deze persoon of organisatie bij betrokken was."
