### ISSUE TITLE
`indicatieGeheimhouding` niet langer verplicht bij aanmaken Partij

### ISSUE THREAD

**Issue by sytskevanhasselt** [maykinmedia/open-klant#207]
### Thema / Theme

Klantinteracties API

### Omschrijving / Description

Op dit moment is het property `indicatieGeheimhouding`  verplicht bij het aanmaken van een klant (zie [POST in openapi.yaml](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/maykinmedia/open-klant/2.1.0/src/openklant/components/klantinteracties/openapi.yaml#tag/partijen/operation/partijenCreate))

Dit zou niet verplicht moeten zijn. 

### Toegevoegde waarde / Added value

**Reden:** 
- de precieze betekenis van het property is onduidelijk. in de specificatie staat "Geeft aan of de verstrekker van partijgegevens heeft aangegeven dat deze gegevens als geheim beschouwd moeten worden." Maar het is niet duidelijk wat de consequentie daarvan is. In een overleg met Team Asterix konden zijn ook niet aangeven wat de betekenis is van het gegeven. 
- Het is niet hetzelfde als het concept [Geheimhouding uit de BRP](https://www.rijksoverheid.nl/onderwerpen/privacy-en-persoonsgegevens/vraag-en-antwoord/waar-vraag-ik-geheimhouding-van-mijn-persoonsgegevens-aan#:~:text=U%20vraagt%EE%80%80%20geheimhouding%EE%80%81). Dat gaat over het delen van je gegevens door de gemeente met bijv. een kerk.

Als je niet zeker weet wat het betekent en je moet het wel opslaan, leidt dat alleen maar tot ruis.

**Comment by joeribekker** [comment]
Refinement: We maken het veld niet meer `required`. Default wordt de nieuwe waarde `null`, en `null` moet dus ook toegestaan worden. Hierbij moet de helpt tekst komen dat `null` betekent dat het niet bekend is dat een Partij heeft aangegeven dat zijn gegevens geheim of niet zijn.
