### ISSUE TITLE
Reductie van het benodigde aantal calls om adhv een digitaaladres InterneTaken te vinden

### ISSUE THREAD

**Issue by mstokericatt** [maykinmedia/open-klant#214]
### Thema / Theme

Klantinteracties API

### Omschrijving / Description

Wanneer je op basis van een telefoonnummer of emailadres InterneTaken wil vinden, zal je eerst de DigitaleAdressen moeten opzoeken. Vervolgens de bijbehorende Betrokkenen. Daarna de daaraan gelinkte KlantContacten en ten slotte kan je daarmee de InterneTaken ophalen. 

Het is wenselijk met minder calls hetzelfde resultaat te kunnen bereiken. Wij hebben geen exacte oplossing voor ogen, maar denken aan uitgebreidere geneste expand mogelijkheden. Bijvoorbeeld expand DigitaalAdres naar Betrokkene en die naar KlantContact en die naar InterneTaak, zodat je met een enkel request op DigitaalAdres alle bijbehorende InterneTaken kan ophalen. Een deel hiervan, in plaats van de hele keten in een keer expanden, zou ook al schelen.

Indien voorgaande niet mogelijk is, zo de toevoeging van extra query parameters een alternatieve oplossingsrichting kunnen zijn. Bijvoorbeeld het opvragen van InterneTaken op basis van een telefoonnummer: /internetaken?digitaaladres__adres=0612345678. 
Nb. het is dan wel noodzakelijk dat alle digitaaladres parameters gebruikt kunnen worden 

### Toegevoegde waarde / Added value

De code voor het opzoeken van contactmomenten (KlantContact) en contactverzoeken (InterneTaak) wordt hiermee een stuk minder bewerkelijk. Minder calls betekent betere performance en minder kans op fouten. De benodigde code wordt eenvoudiger, beter te onderhouden en de kans op bugs wordt kleiner

**Comment by sytskevanhasselt** [comment]
Besproken met @bart-maykin : eerst onderzoeken of het met expand op te lossen is. Daarna weer overleggen.
