### ISSUE TITLE
Send notifications for customers in OpenKlant

### ISSUE THREAD

**Issue by mariusvandam** [maykinmedia/open-klant#224]
### Thema / Theme

Klantinteracties API

### Omschrijving / Description

Support the sending of notifications from OpenKlant (2) upon change/add/delete of customers

### Toegevoegde waarde / Added value

This allows Dimpact to have actions triggered by alterations in OpenKlant: Specifically Dimpact will use them to synchronise customer data between OpenKlant and e-Suite.

**Comment by andyverberne** [comment]
De wens is om notificaties te ontvangen van het aanmaken, bijwerken en verwijderen van een 'Partij'. 
- kanaal (naam van het kanaal): 'partijen'
- resource (De resourcenaam waar de notificatie over gaat): 'partij'
- hoofsobject: URL-referentie naar de betreffende partij
- resourceUrl: URL-referentie naar de betreffende partij

**Comment by mariusvandam** [comment]
@joeribekker is het mogelijk om op basis van de details van Andy met een voorstel/inschatting te komen om deze aanpassing te ontwikkelen?

**Comment by joeribekker** [comment]
Refinement: @SonnyBA can you flesh out the details of this ticket on how you see this?

**Comment by mariusvandam** [comment]
Er is opnieuw discussie over de aanpak voor synchronisatie. Daarom stellen we voor dit ticket nog even On Hold te zetten.

**Comment by joeribekker** [comment]
Dit blijkt toch niet nodig te zijn via Dimpact POD-241.
