### ISSUE TITLE
Fixed set of values for 'soort digitaal adres' (ENUM)

### ISSUE THREAD

**Issue by mariusvandam** [maykinmedia/open-klant#232]
### Thema / Theme

Klantinteracties API

### Omschrijving / Description

- Change the field 'soort digitaal adres' in an ENUM, with a fixed set of supported values including "email" and "telefoonnummer".
- Add an 'overig' (other) option with the option to add a custom type of digital address.

### Toegevoegde waarde / Added value

This ensures consistent use if attribute names for digital addresses and eases retrieval of this data

**Comment by mariusvandam** [comment]
Dimpact backlog: https://dimpact.atlassian.net/browse/POD-245

**Comment by andyverberne** [comment]
Eerste opzet:

- `telefoonnummer`
- `email`
-
