### ISSUE TITLE
Validation of any stored email address

### ISSUE THREAD

**Issue by mariusvandam** [maykinmedia/open-klant#234]
### Thema / Theme

Klantinteracties API

### Omschrijving / Description

It is desirable to have OpenKlant validate any email addresses before storing them so that they are stored in a consistent way.

### Toegevoegde waarde / Added value

This make sure only valid mail addresses are stored and any connected system can rely on the provided addresses.

### Aanvullende opmerkingen / Additional context

As discussed on 29-8 with Andy, ICATT & Maykin

**Comment by sytskevanhasselt** [comment]
At the risk of asking for the obvious: is there documentation of the exact validation, other then in [andyverberne's comment](https://github.com/maykinmedia/open-klant/issues/234#issuecomment-2323883939)? Is this something that one would find in a redoc?

**Comment by joeribekker** [comment]
@SonnyBA is this also in the redoc? It should be :)

**Comment by SonnyBA** [comment]
Meegenomen via f2447afbf28aea8367f49cfa06862119896f6b04
