### ISSUE TITLE
Enforcing uniqueness of Partij Identificatoren

### ISSUE THREAD

**Issue by swrichards** [maykinmedia/open-klant#241]
### Thema / Theme

Klantinteracties API

### Omschrijving / Description

It is currently possible to create:

1. Multiple identical partij identificatoren (i.e. for two resources, the values for `codeObjecttype`, `codeSoortObjectId`, `objectId`, and `codeRegister` are the same)
2. To match multiple identical identificatoren to the same partij

The proposal is to guard against both: partij identificatoren should be unique for the fields mentioned above and thus, by implication, they can only point to a single Partij.

### Toegevoegde waarde / Added value

The proximate pain point here is that, when filtering all `Partij` resources on an identificator, clients have to handle the case of `>1 Partijen for a supposedly unique identificator`, with no obvious resolution strategy.

That is, when filtering on a BSN partij identificator (leaving aside the issue of divergent schemes to refer to a BSN, which #233 would address), it is currently possible to get several `Partij` resources for a single BSN, which should be unique (as arguably _all_ identificatoren are). It is not clear which `Partij` to select. Even if clients have a consistent way of identifying the canonical Partij from several options for a single client (e.g. by maintaining an internal mapping to `Partij.uuid`), this means that several different clients may reference different `Partij` when in fact they intend to converge on the same object.

The value of an identificator should be that it actually functions as a unique identifier, both for developer experience (no difficult-to-resolve edge-cases to handle), but it would also improve the data quality (less chance of spurious duplicates). This would be complementary to #233 .

**Comment by joeribekker** [comment]
Relevant IM deel:
![image](https://github.com/user-attachments/assets/1c0758e0-a238-4240-af76-6b8ec4a11d7e)

Besproken of Contactpersoon wel een instantie moet zijn van Partij. Omdat Contactpersoon een instantie is van een Partij maar ook een Persoon en/of zelfs Contactpersoon kan zijn voor meerdere organisaties, zal zijn/haar BSN meerdere keren voorkomen waarschijnlijk?

**Comment by Hugo-ter-Doest** [comment]
Inderdaad.

Teveel onzekerheid over de scenario's. We bespreken het vanmiddag met de groep die OpenKlant integreert.
