### ISSUE TITLE
Question: Admin-screen Interne Taken does not show `toegewezenAanActoren` or `toegewezenAanActor` ?

### ISSUE THREAD

**Issue by sytskevanhasselt** [maykinmedia/open-klant#245]
### Product versie / Product version

2.2.0

### Omschrijf het probleem / Describe the bug

In many Admin screens of object in OpenKlant2, you can see the value of connected objects. F.i. when viewing a `Klantcontact`, the screen also shows the value of `ActorKlantcontacten` of that klantcontact. 

In this light we would expect to see, on the admin screen of Interne Taken, the value of `toegewezenAanActoren` or at least `toegewezenAanActor`. But it doesn't. See screenshots in comment.

I must  admit I haven't looked at this screen in 2.1.0, so I don't know if this is a result of the fixing of issue #182. 

Where would we be able to see either `toegewezenAanActoren` or at least `toegewezenAanActor` in the admin interface? 

### Stappen om te reproduceren / Steps to reproduce

1. Go To /admin/klantinteracties/internetaak/ in Admin
2. Open a specific Interne Taak.

**Comment by sytskevanhasselt** [comment]
**SCREENSHOT KLANTCONTACT:**

![image](https://github.com/user-attachments/assets/ac3168db-975d-4211-af54-15daee0569a0)

**SCREENSHOT INTERNE TAAK:**
![image](https://github.com/user-attachments/assets/21635eda-f565-46f9-b270-e2d3e29ea667)

**Comment by alextreme** [comment]
Seems to be the same as #251 ?

**Comment by sytskevanhasselt** [comment]
Yes it is, my apologies. I'll close this one
