### ISSUE TITLE
Store default address per 'soort digitaal adres'

### ISSUE THREAD

**Issue by mariusvandam** [maykinmedia/open-klant#246]
### Thema / Theme

Klantinteracties API

### Acceptance criteria
* At any time only a single digital address can be default per 'soort digitaal adress'
* It is possible to set the default
* It is possible to change the default

### Toegevoegde waarde / Added value

In case there are multiple digital addresses of a certain type, it is needed to know which one to use for a certain communication. The existing 'voorkeur digitaal adress' is not enough as that may be an address which cannot be used for a certain communication

**Comment by stevenbal** [comment]
I made the PR draft, because I'm not sure if my implementation is correct, it might be good to discuss this next week: https://github.com/maykinmedia/open-klant/pull/269#issuecomment-2435194388
