### ISSUE TITLE
In Admin interface is Actor aan wie interne Taak is toegewezen niet te zien

### ISSUE THREAD

**Issue by sytskevanhasselt** [maykinmedia/open-klant#251]
### Product versie / Product version

2.2.0

### Omschrijf het probleem / Describe the bug

Als wij een internte taak posten, met daaraan gekoppeld een Actor, dan zien we die relatie niet terug in de Admin-interface. Het lijkt ons wel de bedoeling dat je bij een interneTaak kan zien wie de actor is uit `toegewezenAanActoren`. Omdat je in de AdminInterface bij een Klantcontact ook kunt zien wie de Actor is in `hadBetrokkenActoren`. 

Vice versa zie je ook niet bij een Actor welke interneTaken aan die actor zijn toegewezen. 
Bij Actoren zie je wel welke klantcontacten de actor betrokken was. 

Is dit een bewust verschil in de interface tussen klantcontact en interne taak? 

NB: Bij zowel Klantcontact als bij Actor heeft de interface ook blauwe balken voor gekoppelde Actor of Klantcontact. 
Bij Interne taken is zo'n blauwe balk er niet. 
Bij Actor is ook geen blauwe balk voor interne taken. 

![image](https://github.com/user-attachments/assets/ad6a1f9b-db3b-4de7-a6ab-9ccb460839e3)

![image](https://github.com/user-attachments/assets/82902b88-eaec-40a0-a6bd-13e55b117b95)

**Comment by alextreme** [comment]
Discussed, is likely an inline that should be added
