### ISSUE TITLE
Kan via de beheer-frontend van OpenKlant geen persoon toevoegen zonder overlijdensdatum.

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/open-klant#252]
### Product versie / Product version

2.2

### Omschrijf het probleem / Describe the bug

Taiga Utrecht 290

> In de beheer-frontend van OpenKlant kan ik geen persoon toevoegen zonder daar ook de overlijdensdatum in te vullen. Met andere woorden, ik kan alleen dode mensen op die manier toevoegen. 
Volgens de specificaties zou het niet nodig moeten zijn om die toe te voegen, alleen de geboortedatum. 
Via aan API-call kan ik wel een persoon toevoegen zonder overlijdensdatum, maar als ik die via de frontend oproep, kan ik die niet opslaan zonder eerst een overlijdensdatum in te vullen.

**Comment by joeribekker** [comment]
Estimate: 1/2 day
Waiting for approval from @alexvdL-utrecht

Solution direction: Make the field optional/nullable.

**Comment by joeribekker** [comment]
@alexvdL-utrecht ping
