### ISSUE TITLE
Bij antwoord van API call voor het opvragen of het aanmaken 'persoon' krijg ik een 'organisatie' url terug in de body van het response

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/open-klant#254]
### Product versie / Product version

2.2

### Omschrijf het probleem / Describe the bug

Taiga Utrecht 289

> 
> Als ik van een persoon via een API-call de gegevens opvraag, staat er in de json in het veld url de verkeerde url, namelijk, bijvoorbeeld
> 
> "url": "https://openklant/contactgegevens/api/v1/organisatie/7ef275bc-6eec-4f81-80ba-1892f2c8eea6",
> 
> in plaats van wat ik zou verwachten en zoals de gebruikte URL is:
> 
> "url": "https://openklant/contactgegevens/api/v1/persoon/7ef275bc-6eec-4f81-80ba-1892f2c8eea6",
> 
> Het verschil zit hem in organisatie respectievelijk persoon.
> 
> Als ik de url gebruik die in het antwoord zit, krijg ik een 404.
> 
> 
> Aanvulling: in de reply bij het aanmaken van een persoon via een API-call staat bij de url ook organisatie in plaats van persoon.

Bevestigd via: test_create_persoon (openklant.components.contactgegevens.api.tests.test_apis.PersoonTests.test_create_persoon)

Response:

`{'uuid': 'c8410f1d-0c1c-43c5-ad43-6598bae939a7', 'url': 'http://testserver/contactgegevens/api/v1/organisatie/c8410f1d-0c1c-43c5-ad43-6598bae939a7', 'geboortedatum': '1972-05-05', 'overlijdensdatum': None, 'geslachtsnaam': 'Townsend', 'geslacht': 'm', 'voorvoegsel': '', 'voornamen': 'Devin', 'adres': {'nummeraanduidingId': 'nummeraanduiding_id', 'adresregel1': 'adresregel1', 'adresregel2': 'adresregel2', 'adresregel3': 'adresregel3', 'land': '5001'}, 'land': '5001'}`

**Comment by joeribekker** [comment]
Needs stakeholder

**Comment by joeribekker** [comment]
Estimate: 1 day
Waiting for approval from @alexvdL-utrecht
