### ISSUE TITLE
Hoe haal ik alle klantcontacten bij een partij op

### ISSUE THREAD

**Issue by flinden68** [maykinmedia/open-klant#264]
### Product versie / Product version

0.0.3

### Omschrijf het probleem / Describe the bug

Er is de mogelijkheid om klantcontacten bij een partij op te halen via de expand parameter. Ik kan digitale addressen wel direct ophalen door aan de expand parameter digitaleAdressen toe te voegen. Maar hoe doe ik dat bij klantcontacten?
lijkt of deze 'genest' is in een betrokkene

**Comment by alextreme** [comment]
Most likely a matter of providing the correct relations via the expand parameter, not confirmed as a bug

**Comment by SonnyBA** [comment]
[This issue](https://github.com/maykinmedia/open-klant/issues/256) describes two methods to achieve this. [Note that work is being done](https://github.com/maykinmedia/open-klant/pull/285) to make this a lot easier to achieve the same result (through query parameters like one might expect).
