### ISSUE TITLE
Als projectmanager wil ik per kanaal aangeven wat het voorkeurs adres is

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#68]
.. zodat ik precies weet wat hoe ik iemand het beste kan benaderen.

In het huidige informatiemodel kan ik nu enkel aangeven dat "email" of "telefoon", mijn voorkeurskanaal is. Ik kan echter niet opgeven dat mijn voorkeurskanaal "joeri@example.com". Als ik dus meerdere emailadressen heb, dan weet ik als gemeente nog steeds niet waar het heen moet.

**Comment by EvdMerwe** [comment]
Voor Amsterdam Erfpacht is dit een nice to have maar geen must.

**Comment by joeribekker** [comment]
Dit is nu mogelijk doordat er een relatie is gemaakt in versie 0.7 van het IM van VNG Partij->gaf voorkeur aan voor contact via->Digitaal adres
