### ISSUE TITLE
Als koploper wil ik aanvullingen op `Persoon` die nog niet in het informatiemodel van VNG zitten

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#70]
.. zodat ik mijn praktische use case kan invullen.

Uit Excel:
![image](https://github.com/maykinmedia/open-klant/assets/96970/dfd1b64f-96e8-482e-a7d4-436e227db649)
![image](https://github.com/maykinmedia/open-klant/assets/96970/e194905a-d3b9-47f3-ba10-5e1f77431e20)

* [ ] Add `geboortedatum` and `overlijdendatum to `Persoon`

**Discuss**

* [x] Moet dit ook bij `Contactpersoon`? -> Nee, enkel `Persoon`
* [x] Uitstaande vraag in Excel: Moet `overlijdendatum` en indicatie worden? -> Nee, zie hieronder!

**Comment by EvdMerwe** [comment]
Overlijdensdatum is een gegeven dat benodigd is voor processturing binnen Erfpacht. Het is benodigd voor natuurlijke personen, maar niet voor contactpersonen. Daar volstaat een aanduiding geldig/niet geldig met datum. 
Geboortedatum is benodigd voor natuurlijke personen die niet in de BRP voorkomen. 
Een indicatie overlijden is handig als de daadwerkelijke overlijdensdatum nog niet bekend is. Hiermee kunnen processen gestart worden.

**Comment by joeribekker** [comment]
@EvdMerwe ik neem dit op in het aparte "Contactgegevens" register omdat deze gegevens anders al via de BRP beschikbaar zouden zijn.

We gaan dit doen via ticket #97
