### ISSUE TITLE
Als Erfpacht-ontwikkelaar wil ik graag meer persoonsgegevens opslaan bij klanten

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#71]
.. zodat ik ook personen kan benaderen die niet in de BRP staan.

In overeenstemming met het uitgangspunt "We maken geen kopie van gegevens uit de BRP" gaat dit dus enkel over persoonsgegevens waarvan de persoon niet in de BRP staat. De API kan een validatie maken dat als er een BSN bekend is, dat deze gegevens niet mogen worden opgeslagen.

Aangeleverde lijst attributen:

- Klantnummer (verplicht)

**Natuurlijk persoon (allemaal optioneel):**

- Geboortedatum _(overlapt #70)_
- Geslachtsnaam _(reeds aanwezig)_
- Geslacht
- Voorvoegsel _(reeds aanwezig)_
- Voornamen _(reeds aanwezig)_
- ~Burgerservicenummer~ (deze is er dus niet)
- Verblijfplaats__postcode
- Verblijfplaats__huisnummer
- Verblijfplaats__straat

**Organisaties (allemaal optioneel)**

- ~KVK nummer~(deze is er dus niet)
- ~RSIN~ (deze is er dus niet)
- Handelsnaam (=naam?)
- Straatnaam
- Huisnummer
- Huisnummertoevoeging
- Postcode
- Plaats
- Type  

**Discuss**

* [x] Een aantal attributen zijn "reeds aanwezig" (zie boven) maar deze hebben een andere intentie dan BRP-achtige gegevens opslaan voor mensen die niet in de BRP staan. Ze moeten dus dubbel?
* [x] VNG akkoord?
* [ ] Koplopers akkoord?

**Comment by hdksi** [comment]
Klopt het dat we het in user story hebben over personen waarvan in de BRP of RNI geen gegevens zijn geregistreerd? Over deze categorie hebben we naar aanleiding van de bespreking van het informatiemodel een paar weken geleden een uitspraak gedaan (die makkelijker is gezegd dan gedaan, want er zijn voor opslag voor deze categorie personen geen gestandaardiseerde 'vervangende' registers beschikbaar):

![CIMP2](https://github.com/maykinmedia/open-klant/assets/37660390/85d134b6-507a-4f6f-9efa-b62613ffff8e)

Hiermee is uiteraard niet gezegd dat die uitspraak niet kan worden teruggedraaid. Maar of dat wenselijk is vind ik lastig te beoordelen zonder casus die de wens ondersteunt.

**Comment by joeribekker** [comment]
@hdksi Volgens mij beschrijf jij wat ik in de user story heb gevat onder:

> In overeenstemming met het uitgangspunt "We maken geen kopie van gegevens uit de BRP" gaat dit dus enkel over persoonsgegevens waarvan de persoon niet in de BRP staat.

Jij schrijft:
> Klopt het dat we het in user story hebben over personen waarover in de BRP of RNI überhaupt geen gegevens zijn geregistreerd?

Dat klopt.

> Dat is wat mij betreft een ander geval dan de situatie waarin gegevens over personen wel in de BRP of RNI bekend zijn, maar we die niet mogen verwerken. Ik meende dat vooral die laatste in relatie tot de erfpachtcasus relevant was.

Dat klopt ook. Nieuw hierin is (van wat ik er van heb begrepen, in een gesprek afgelopen maandag met Amsterdam) dat zij toch toegang gaan krijgen tot de BRP voor deze casus.

**Comment by Stefanieams** [comment]
Het klopt wat Joeri zegt (afgezien van het feit dat het niet nieuw is, maar voor erfpacht altijd al zo was): het gaat om opslaan van gegevens van partijen die niet een ander basisregister staan (niet in BRP, niet RNI en niet in KVK). Met deze partijen doen wij wel zaken en omdat we hun gegevens nergens kunnen ophalen, moeten we ze zelf opslaan. Het gaat hier om hetzelfde type gegevens als we voor de andere partijen ophalen uit BRP/KVK.
Als we BRP gegevens nodig hebben, dan kunnen deze worden opgehaald door de gebruikers die daar de juiste rechten voor hebben in de applicatie.

**Comment by Stefanieams** [comment]
Een aantal attributen zijn "reeds aanwezig" (zie boven) maar deze hebben een andere intentie dan BRP-achtige gegevens opslaan voor mensen die niet in de BRP staan. Ze moeten dus dubbel?
--> als je wilt afdwingen dat deze niet door de gebruiker gevuld mogen worden indien een BSN bestaat, dan zullen je ze misschien dubbel moeten maken? Functioneel gezien maakt het mij als gebruiker niet zo heel veel uit, uit welke bron een naam of een adres komt.  Aan de aan- of afwezigheid van een BSN/KVK nummer zou ik moeten kunnen zien of de gegevens uit een basisregistratie komen of uit mijn eigen klantregistratie (ivm zekerheid actualiteit misschien handig)

**Comment by hdksi** [comment]
Dankjewel @Stefanieams. De bedoeling is volgens mij helder.

@joeribekker merkt terecht op dat voor wat betreft bepaalde gegevens (namen, adressen) in vorm, maar niet in betekenis (een bezoekadres hoeft niet het formele verblijfs- of vestigingsadres te zijn), doel en mate van 'formaliteit' overlap bestaat tussen de BRP en het Handelsregister enerzijds en het Klantinteractiesregister anderzijds. Het minder 'formele' karakter van klantinteractiegegevens is belangrijk. Waar personen en organisaties naar eigen inzicht hun klantinteractiegegevens kunnen verstrekken en wijzigingen, moeten mutaties van gegevens in basisregistraties veelal worden ondersteund door bewijsstukken. Ze kunnen dus niet 'zomaar' door betrokken personen en organisaties gewijzigd worden.

Hieruit volgt dat er, aanvullend bij registratie van klantinteractiegegevens, twee redenen kunnen zijn voor het bijhouden van 'basisgegevens' over niet in Nederlandse basisregistraties gekende personen en organisaties:

1. we hebben gegevens nodig (bijvoorbeeld een formele handelsnaam of officieel verblijfsadres) die qua vorm wel aansluiten bij gegevens die binnen klantinteracties kunnen worden vastgelegd (zie organisatienaam en bezoekadres), maar niet qua 'formaliteit'. Of anders gezegd: we willen niet dat een klant zomaar een door ons formeel vastgestelde naam of adres kan wijzigen.
2. we hebben gegevens nodig (bijvoorbeeld een geboortedatum of informatie over de rechtsvorm van een organisatie) die eenvoudigweg binnen klantinteracties niet passen.

Naar aanleiding daarvan ontstaan twee vragen:

1. zijn 'formele' 'basisgegevens' zoals een verblijfsadres of een vestigingsadres nodig om het erfpachtdomein te ondersteunen?
2. hoe controleer je voor personen of organisaties waarover in Nederlandse basisregistraties geen gegevens zijn opgenomen of een opgegeven verblijfsadres of vestigingsadres ook echt het 'formele' verblijfsadres of een vestigingsadres is? Is controle daarvan niet of beperkt mogelijk, dan zijn over deze personen of organisaties vastgelegde 'basisgegevens' niet 'bruikbaarder' dan een door zo'n persoon of organisatie verstrekt bezoek- of correspondentieadres.

Als uit antwoorden op deze vragen blijkt dat het inderdaad nodig is om 'basisgegevens' over personen en organisaties die we in de Nederlandse basisregistraties niet kennen bij te houden, ligt het voor de hand dit in Open Klant te doen. We kennen hiervoor immers (nog) geen gestandaardiseerde (kern)registers. Om het ontstaan van zulke registers in de toekomst niet in de weg te staan, stel ik voor om deze 'basisgegevens' te scheiden van 'partijgegevens' en de relatie daartussen te leggen middels een externe identificatie. Zie de illustratie hieronder (voor personen, maar voor organisaties kan een gelijkaardig patroon worden gevolgd):

![20231011 - Niet-BRP-gekende personen in Open Klant](https://github.com/maykinmedia/open-klant/assets/37660390/f65c85b1-fa66-412f-919e-a06b69544e3d)

**Comment by joeribekker** [comment]
In overleg met VNG kunnen persoonsgegevens die niet in de BRP/RNI staan, in een apart register worden opgeslagen. Dit register wordt echter geen onderdeel van de Klantinteracties API.

Voor praktische redenen neem ik dit register (en API) wel op in Open Klant, zodat dit opgeslagen kan worden. Dit is volgens VNG ook precies de bedoeling zodat er gekoppeld kan worden tussen personen in dit register en `Partij` via `ExterneRegistratie` (in IM 004) of `Partij-identificator` (in IM 006).

**Comment by joeribekker** [comment]
Met de toevoeging van `Contactgegevens API` in Open Klant gaat dit kunnen. Dit is toegevoegd via #109 en ticket #97 .

Ik ben nog niet heel gelukkig met de naam. Het lijkt meer te dekken dan het doet, en dan wordt het wellicht ook zo gebruikt.

Maar ja, "Register van niet-geregistreerde personen" is ook zo...
